//! Compile an Agenomic genome into per-framework runtime adapters.
//!
//! This is the `genome → runtime` step of the `agent-bundle` format: the
//! declarative `genome.yaml` is lowered into runnable source under
//! `runtime/<target>.compiled/`. Targets today: [`CompileTarget::Plain`]
//! (FastAPI + provider SDK), [`CompileTarget::LangGraph`], and
//! [`CompileTarget::CrewAi`].
//!
//! Design invariants (consistent with the rest of the workspace):
//! - **Deterministic.** For a fixed genome, the generated bytes are stable:
//!   files live in a `BTreeMap`, there are no timestamps, and the manifest
//!   lists files in sorted order with BLAKE3 digests.
//! - **Offline.** Generation reads the bundle and writes source; it never
//!   touches the network or a model provider.
//! - **Self-contained output.** Each compiled tree embeds its prompts and a
//!   `manifest.json` pinning every file plus the source genome hash, so a
//!   downstream attestation can sign exactly what was emitted.
//!
//! ```no_run
//! use agenomic_compile::{compile_bundle, CompileTarget};
//! let artifacts = compile_bundle(std::path::Path::new("./my-bundle"),
//!                                &[CompileTarget::Plain]).unwrap();
//! assert_eq!(artifacts.len(), 1);
//! ```

mod artifact;
mod codegen;
mod error;
mod genome;
mod target;

use std::path::Path;

pub use artifact::{blake3_hex, CompiledArtifact, FileDigest, Manifest, GENERATOR};
pub use error::{CompileError, CompileResult};
pub use genome::{Genome, GenomeSpec};
pub use target::CompileTarget;

/// Compile a single in-memory [`Genome`] for one `target`, returning a
/// finished [`CompiledArtifact`] (prompts embedded, `manifest.json` attached).
pub fn compile(genome: &Genome, target: CompileTarget) -> CompileResult<CompiledArtifact> {
    let mut artifact = codegen::generate(genome, target);
    codegen::embed_prompts(genome, &mut artifact);

    let source_hash = blake3_hex(canonical_genome_bytes(genome).as_bytes());
    artifact.attach_manifest(
        &genome.spec.agent.id,
        &genome.spec.runtime.model_id,
        &source_hash,
    )?;
    Ok(artifact)
}

/// Load the genome at `bundle_dir` and compile it for each of `targets`,
/// returning the finished artifacts (not yet written to disk).
pub fn compile_bundle(
    bundle_dir: &Path,
    targets: &[CompileTarget],
) -> CompileResult<Vec<CompiledArtifact>> {
    let genome = Genome::load(bundle_dir)?;
    targets.iter().map(|t| compile(&genome, *t)).collect()
}

/// Compile and write the artifacts under `bundle_dir/runtime/<t>.compiled/`,
/// returning, for each target, the directory written.
pub fn compile_and_emit(
    bundle_dir: &Path,
    targets: &[CompileTarget],
) -> CompileResult<Vec<(CompileTarget, std::path::PathBuf)>> {
    let artifacts = compile_bundle(bundle_dir, targets)?;
    let mut written = Vec::with_capacity(artifacts.len());
    for artifact in artifacts {
        let dir = artifact.emit_to_bundle(bundle_dir)?;
        written.push((artifact.target, dir));
    }
    Ok(written)
}

/// Canonical bytes of the genome used for the `source_genome_hash`. We
/// re-serialize the parsed spec so the hash is insensitive to YAML formatting
/// noise (comments, key order) and stable across equivalent inputs.
fn canonical_genome_bytes(genome: &Genome) -> String {
    // Serialize via serde_json (deterministic field order from the struct) so
    // two formatting-different-but-equivalent genomes hash identically.
    serde_json::json!({
        "agent_id": genome.spec.agent.id,
        "model_provider": genome.spec.runtime.model_provider,
        "model_id": genome.spec.runtime.model_id,
        "temperature": genome.spec.runtime.temperature,
        "skills": genome.skill_prompts.iter().map(|s| &s.name).collect::<Vec<_>>(),
        "tools": genome.spec.tools.iter().map(|t| &t.name).collect::<Vec<_>>(),
    })
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    const GENOME: &str = r#"
spec_version: '0.1'
agent:
  id: 'agent://treans/claims-agent'
  name: 'Claims Agent'
  domain: 'insurance'
  criticality: 'high'
  description: 'Triages claims.'
runtime:
  model_provider: 'openai'
  model_id: 'gpt-4o'
  temperature: 0.0
tools:
  - name: 'classify_claim'
    protocol: 'mcp'
    server: 'mcp://internal/claims'
    version: '1.2.0'
skills:
  - name: 'classify_claim'
    prompt: 'prompts/skills/classify_claim.md'
  - name: 'compensation_reasoning'
    prompt: 'prompts/skills/compensation_reasoning.md'
knowledge: []
policies: []
"#;

    fn fixture_bundle() -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("prompts/skills")).unwrap();
        std::fs::write(dir.path().join("genome.yaml"), GENOME).unwrap();
        std::fs::write(dir.path().join("prompts/system.md"), "You triage claims.").unwrap();
        std::fs::write(
            dir.path().join("prompts/skills/classify_claim.md"),
            "Classify.",
        )
        .unwrap();
        std::fs::write(
            dir.path().join("prompts/skills/compensation_reasoning.md"),
            "Reason about compensation.",
        )
        .unwrap();
        dir
    }

    #[test]
    fn compiles_all_targets_with_expected_entrypoints() {
        let dir = fixture_bundle();
        let arts = compile_bundle(dir.path(), &CompileTarget::ALL).unwrap();
        assert_eq!(arts.len(), 3);

        let plain = &arts[0];
        assert_eq!(plain.target, CompileTarget::Plain);
        assert!(plain.files.contains_key("agent.py"));
        assert!(plain.files.contains_key("manifest.json"));
        assert!(plain.files.contains_key("prompts/system.md"));
        // Embedded skill prompt content is carried through.
        assert_eq!(
            plain.files.get("prompts/skills/classify_claim.md").unwrap(),
            "Classify."
        );

        assert!(arts[1].files.contains_key("graph.py"));
        assert!(arts[2].files.contains_key("crew.py"));
    }

    #[test]
    fn output_is_deterministic() {
        let dir = fixture_bundle();
        let a = compile_bundle(dir.path(), &[CompileTarget::LangGraph]).unwrap();
        let b = compile_bundle(dir.path(), &[CompileTarget::LangGraph]).unwrap();
        assert_eq!(
            a[0].files, b[0].files,
            "same genome must compile identically"
        );
    }

    #[test]
    fn manifest_pins_source_genome_hash_and_files() {
        let dir = fixture_bundle();
        let arts = compile_bundle(dir.path(), &[CompileTarget::Plain]).unwrap();
        let raw = arts[0].files.get("manifest.json").unwrap();
        let m: serde_json::Value = serde_json::from_str(raw).unwrap();
        assert_eq!(m["target"], "plain");
        assert!(m["source_genome_hash"].as_str().unwrap().len() == 64);
        assert!(!m["files"].as_array().unwrap().is_empty());
    }

    #[test]
    fn generated_python_references_model_and_skills() {
        let dir = fixture_bundle();
        let arts = compile_bundle(dir.path(), &[CompileTarget::Plain]).unwrap();
        let agent = arts[0].files.get("agent.py").unwrap();
        assert!(agent.contains("gpt-4o"));
        assert!(agent.contains("classify_claim"));
        assert!(agent.contains("compensation_reasoning"));
        assert!(agent.contains("openai.OpenAI"));
    }

    #[test]
    fn anthropic_provider_selects_anthropic_sdk() {
        let dir = tempfile::tempdir().unwrap();
        let g = GENOME.replace("model_provider: 'openai'", "model_provider: 'anthropic'");
        std::fs::write(dir.path().join("genome.yaml"), g).unwrap();
        let arts = compile_bundle(dir.path(), &[CompileTarget::Plain]).unwrap();
        let agent = arts[0].files.get("agent.py").unwrap();
        assert!(agent.contains("anthropic.Anthropic"));
        assert!(agent.contains("ANTHROPIC_API_KEY"));
        let reqs = arts[0].files.get("requirements.txt").unwrap();
        assert!(reqs.contains("anthropic"));
    }

    #[test]
    fn emit_writes_runtime_tree() {
        let dir = fixture_bundle();
        let written = compile_and_emit(dir.path(), &[CompileTarget::Plain]).unwrap();
        assert_eq!(written.len(), 1);
        let runtime_dir = dir.path().join("runtime/plain.compiled");
        assert!(runtime_dir.join("agent.py").is_file());
        assert!(runtime_dir.join("manifest.json").is_file());
        assert!(runtime_dir.join("prompts/system.md").is_file());
    }
}
