//! Structured test scenarios: the unit of Review coverage.
//!
//! A scenario binds an input fixture to expected outputs, expected tool
//! calls, expected memory behavior, expected intent, forbidden behaviors,
//! and policy expectations. Scenarios can be authored by hand, generated by
//! the data-engine, or derived from Monitor/Protect findings through the
//! enrichment loop ([`crate::enrich`]).

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

use agenomic_core::{CliError, CliResult, Severity};

/// Version stamped on scenarios.
pub const SCENARIO_VERSION: &str = "agenomic.rmp.scenario/v0.1";

/// Where a scenario came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Hash)]
#[serde(rename_all = "snake_case")]
pub enum ScenarioSource {
    Manual,
    Generated,
    IncidentDerived,
    MonitorDerived,
    ProtectDerived,
    UserProvided,
}

impl ScenarioSource {
    /// Stable snake_case label (matches the serde encoding).
    pub fn label(self) -> &'static str {
        match self {
            Self::Manual => "manual",
            Self::Generated => "generated",
            Self::IncidentDerived => "incident_derived",
            Self::MonitorDerived => "monitor_derived",
            Self::ProtectDerived => "protect_derived",
            Self::UserProvided => "user_provided",
        }
    }
}

/// One input fixture of a scenario. `input` is arbitrary JSON; hashes are
/// preferred for sensitive payloads.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TestScenarioInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub input: serde_json::Value,
    /// `blake3:`-hash of the original payload when `input` is redacted.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub input_hash: Option<String>,
}

/// One expected output of a scenario. Checks are deterministic and are
/// evaluated by the behavior-contract machinery during replay.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TestScenarioExpectedOutput {
    /// `equals` | `contains` | `json_field_present` | `matches_hash`.
    pub check: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
    /// JSON pointer or field name when `check` targets a field.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub field: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_hash: Option<String>,
}

/// A structured test scenario.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TestScenario {
    pub spec_version: String,
    pub scenario_id: String,
    pub title: String,
    #[serde(default)]
    pub description: String,
    pub source: ScenarioSource,
    pub agent_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub genome_hash: Option<String>,
    /// Risk items this scenario covers.
    #[serde(default)]
    pub risk_ids: Vec<String>,
    #[serde(default)]
    pub workflow_step_ids: Vec<String>,
    #[serde(default)]
    pub inputs: Vec<TestScenarioInput>,
    #[serde(default)]
    pub expected_outputs: Vec<TestScenarioExpectedOutput>,
    /// Tool names expected to be called (in order-insensitive set semantics).
    #[serde(default)]
    pub expected_tool_calls: Vec<String>,
    /// `read_only` | `bounded_writes` | `no_memory` | free-form description.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_memory_behavior: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_intent: Option<String>,
    /// Behaviors that must NOT occur (tool names, intents, output markers).
    #[serde(default)]
    pub forbidden_behaviors: Vec<String>,
    /// Policy rule ids expected to allow (or `deny:<rule>` expected to deny).
    #[serde(default)]
    pub policy_expectations: Vec<String>,
    #[serde(default)]
    pub metrics_to_compute: Vec<String>,
    pub severity: Severity,
    #[serde(default)]
    pub tags: Vec<String>,
    pub created_at: DateTime<Utc>,
    #[serde(default)]
    pub created_by: String,
    /// Finding/event/ledger references that motivated this scenario.
    #[serde(default)]
    pub evidence_source_refs: Vec<String>,
    /// Data-engine dataset references backing the fixtures.
    #[serde(default)]
    pub dataset_refs: Vec<String>,
}

impl TestScenario {
    /// Create a minimal scenario.
    ///
    /// ```
    /// use agenomic_rmp::scenario::{ScenarioSource, TestScenario};
    /// use agenomic_core::Severity;
    /// let s = TestScenario::new(
    ///     "agent://acme/claims",
    ///     "Refund loop regression",
    ///     ScenarioSource::MonitorDerived,
    ///     Severity::High,
    /// );
    /// assert!(s.scenario_id.starts_with("sc_"));
    /// ```
    pub fn new(
        agent_id: impl Into<String>,
        title: impl Into<String>,
        source: ScenarioSource,
        severity: Severity,
    ) -> Self {
        Self {
            spec_version: SCENARIO_VERSION.into(),
            scenario_id: format!("sc_{}", ulid::Ulid::new()),
            title: title.into(),
            description: String::new(),
            source,
            agent_id: agent_id.into(),
            genome_hash: None,
            risk_ids: Vec::new(),
            workflow_step_ids: Vec::new(),
            inputs: Vec::new(),
            expected_outputs: Vec::new(),
            expected_tool_calls: Vec::new(),
            expected_memory_behavior: None,
            expected_intent: None,
            forbidden_behaviors: Vec::new(),
            policy_expectations: Vec::new(),
            metrics_to_compute: Vec::new(),
            severity,
            tags: Vec::new(),
            created_at: Utc::now(),
            created_by: String::new(),
            evidence_source_refs: Vec::new(),
            dataset_refs: Vec::new(),
        }
    }

    /// Convert to a behavior-contract trace envelope so the scenario can be
    /// evaluated by the existing deterministic replay checks.
    pub fn to_trace_envelopes(&self) -> Vec<agenomic_contract::TraceEnvelope> {
        self.inputs
            .iter()
            .enumerate()
            .map(|(i, input)| agenomic_contract::TraceEnvelope {
                trace_id: format!("{}#{}", self.scenario_id, i),
                agent_id: self.agent_id.clone(),
                input: input.input.clone(),
                output: None,
                tool_calls: Vec::new(),
                metadata: Some(serde_json::json!({
                    "scenario_id": self.scenario_id,
                    "source": self.source.label(),
                })),
            })
            .collect()
    }
}

/// Validate a scenario's structural invariants.
///
/// ```
/// use agenomic_rmp::scenario::{validate_scenario, ScenarioSource, TestScenario};
/// use agenomic_core::Severity;
/// let s = TestScenario::new("agent://acme/claims", "t", ScenarioSource::Manual, Severity::Low);
/// assert!(validate_scenario(&s).is_ok());
/// ```
pub fn validate_scenario(scenario: &TestScenario) -> CliResult<()> {
    if scenario.scenario_id.is_empty() {
        return Err(CliError::Schema("scenario_id must not be empty".into()));
    }
    if scenario.title.is_empty() {
        return Err(CliError::Schema("scenario title must not be empty".into()));
    }
    if !scenario.agent_id.starts_with("agent://") {
        return Err(CliError::Schema(format!(
            "agent_id must be an agent:// URI, got {:?}",
            scenario.agent_id
        )));
    }
    for out in &scenario.expected_outputs {
        let known = ["equals", "contains", "json_field_present", "matches_hash"];
        if !known.contains(&out.check.as_str()) {
            return Err(CliError::Schema(format!(
                "unknown expected-output check {:?} (known: {})",
                out.check,
                known.join(", ")
            )));
        }
        if out.check == "matches_hash" && out.output_hash.is_none() {
            return Err(CliError::Schema(
                "matches_hash check requires output_hash".into(),
            ));
        }
    }
    for input in &scenario.inputs {
        if let Some(h) = &input.input_hash {
            if !h.starts_with("blake3:") {
                return Err(CliError::Schema(format!(
                    "input_hash must be blake3:-prefixed, got {h:?}"
                )));
            }
        }
    }
    Ok(())
}

/// Parse scenarios from a JSON document holding either a single scenario or
/// an array of scenarios.
pub fn parse_scenarios(text: &str) -> CliResult<Vec<TestScenario>> {
    let value: serde_json::Value = serde_json::from_str(text)
        .map_err(|e| CliError::Schema(format!("scenario JSON: {e}")))?;
    let scenarios: Vec<TestScenario> = if value.is_array() {
        serde_json::from_value(value).map_err(|e| CliError::Schema(format!("scenarios: {e}")))?
    } else {
        vec![serde_json::from_value(value)
            .map_err(|e| CliError::Schema(format!("scenario: {e}")))?]
    };
    for s in &scenarios {
        validate_scenario(s)?;
    }
    Ok(scenarios)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validate_rejects_bad_agent_id() {
        let mut s = TestScenario::new("not-a-uri", "t", ScenarioSource::Manual, Severity::Low);
        s.agent_id = "not-a-uri".into();
        assert!(validate_scenario(&s).is_err());
    }

    #[test]
    fn validate_rejects_unknown_check() {
        let mut s = TestScenario::new(
            "agent://a/b",
            "t",
            ScenarioSource::Manual,
            Severity::Low,
        );
        s.expected_outputs.push(TestScenarioExpectedOutput {
            check: "regex".into(),
            value: None,
            field: None,
            output_hash: None,
        });
        assert!(validate_scenario(&s).is_err());
    }

    #[test]
    fn parse_single_and_array() {
        let s = TestScenario::new(
            "agent://a/b",
            "t",
            ScenarioSource::Manual,
            Severity::Low,
        );
        let one = serde_json::to_string(&s).unwrap();
        let many = format!("[{one}]");
        assert_eq!(parse_scenarios(&one).unwrap().len(), 1);
        assert_eq!(parse_scenarios(&many).unwrap().len(), 1);
    }

    #[test]
    fn trace_envelope_conversion() {
        let mut s = TestScenario::new(
            "agent://a/b",
            "t",
            ScenarioSource::Manual,
            Severity::Low,
        );
        s.inputs.push(TestScenarioInput {
            name: None,
            input: serde_json::json!({"claim": 1}),
            input_hash: None,
        });
        let envs = s.to_trace_envelopes();
        assert_eq!(envs.len(), 1);
        assert_eq!(envs[0].agent_id, "agent://a/b");
    }
}
