//! Helpers shared by every target generator.

use crate::artifact::CompiledArtifact;
use crate::genome::{py_ident, Genome};

/// Provider package + client snippet shared by the generators.
pub(crate) struct Provider {
    /// pip requirement line, e.g. `openai>=1.0`.
    pub requirement: &'static str,
    /// Human label for headers.
    pub label: &'static str,
}

/// Map a genome `model_provider` to its SDK requirement. Unknown providers
/// fall back to OpenAI-compatible, which is the most common shape.
pub(crate) fn provider_for(name: &str) -> Provider {
    match name.trim().to_ascii_lowercase().as_str() {
        "anthropic" => Provider {
            requirement: "anthropic>=0.40",
            label: "Anthropic",
        },
        "google" | "google-generativeai" | "vertexai" => Provider {
            requirement: "google-generativeai>=0.8",
            label: "Google",
        },
        _ => Provider {
            requirement: "openai>=1.40",
            label: "OpenAI",
        },
    }
}

/// Required env var the generated client reads for credentials.
pub(crate) fn api_key_env(provider: &str) -> &'static str {
    match provider.trim().to_ascii_lowercase().as_str() {
        "anthropic" => "ANTHROPIC_API_KEY",
        "google" | "google-generativeai" | "vertexai" => "GOOGLE_API_KEY",
        _ => "OPENAI_API_KEY",
    }
}

/// Embed the system prompt and each skill prompt into the artifact under
/// `prompts/`, so the compiled tree is self-contained and portable. Skills
/// without resolved text get a placeholder so the file always exists.
pub(crate) fn embed_prompts(genome: &Genome, artifact: &mut CompiledArtifact) {
    if let Some(system) = &genome.system_prompt {
        artifact.insert("prompts/system.md", system.clone());
    } else {
        artifact.insert(
            "prompts/system.md",
            format!(
                "# System prompt for {}\n\n(No prompts/system.md in the source bundle.)\n",
                genome.spec.agent.name
            ),
        );
    }
    for skill in &genome.skill_prompts {
        let body = skill.text.clone().unwrap_or_else(|| {
            format!(
                "# {} skill\n\n(No prompt file resolved for this skill in the source bundle.)\n",
                skill.name
            )
        });
        artifact.insert(format!("prompts/skills/{}.md", py_ident(&skill.name)), body);
    }
}

/// Standard generated-file banner.
pub(crate) fn banner(genome: &Genome, target_label: &str) -> String {
    format!(
        "# Auto-generated by agenomic-compile (target: {target_label}).\n\
         # Source agent: {}\n\
         # DO NOT EDIT BY HAND — regenerate with `agenomic compile`.\n",
        genome.spec.agent.id
    )
}

/// Render the skills registry as a Python dict literal mapping skill name →
/// prompt file. Deterministic (genome declaration order).
pub(crate) fn skills_dict(genome: &Genome) -> String {
    if genome.skill_prompts.is_empty() {
        return "{}".to_string();
    }
    let mut s = String::from("{\n");
    for skill in &genome.skill_prompts {
        s.push_str(&format!(
            "    {:?}: PROMPT_DIR / \"skills\" / {:?},\n",
            skill.name,
            format!("{}.md", py_ident(&skill.name))
        ));
    }
    s.push('}');
    s
}

/// Render the declared tools as a Python list of dict literals (stub bindings).
pub(crate) fn tools_list(genome: &Genome) -> String {
    if genome.spec.tools.is_empty() {
        return "[]".to_string();
    }
    let mut s = String::from("[\n");
    for tool in &genome.spec.tools {
        s.push_str(&format!(
            "    {{\"name\": {:?}, \"protocol\": {:?}, \"server\": {:?}, \"version\": {:?}}},\n",
            tool.name,
            tool.protocol.clone().unwrap_or_default(),
            tool.server.clone().unwrap_or_default(),
            tool.version.clone().unwrap_or_default(),
        ));
    }
    s.push(']');
    s
}

/// Python float literal for the model temperature, defaulting to 0.0.
pub(crate) fn temperature_literal(genome: &Genome) -> String {
    let t = genome.spec.runtime.temperature.unwrap_or(0.0);
    // Keep it a float literal even for whole numbers.
    if t.fract() == 0.0 {
        format!("{t:.1}")
    } else {
        format!("{t}")
    }
}
