//! `crewai` target: a Crew with one Task per skill, executed sequentially.

use crate::artifact::CompiledArtifact;
use crate::codegen::common::{api_key_env, banner, provider_for, temperature_literal};
use crate::genome::{py_ident, Genome};
use crate::target::CompileTarget;

pub(crate) fn generate(genome: &Genome) -> CompiledArtifact {
    let mut a = CompiledArtifact::new(CompileTarget::CrewAi);
    let provider = provider_for(&genome.spec.runtime.model_provider);
    let key_env = api_key_env(&genome.spec.runtime.model_provider);

    a.insert("crew.py", crew_py(genome, key_env));
    a.insert(
        "requirements.txt",
        format!("crewai>=0.51\n{}\n", provider.requirement),
    );
    a.insert("README.md", readme(genome, provider.label, key_env));
    a
}

fn crew_py(genome: &Genome, key_env: &str) -> String {
    // Build one Task per skill; an agent with no skills gets a single
    // pass-through task driven by the system prompt.
    let mut tasks = String::new();
    let mut task_names = Vec::new();
    if genome.skill_prompts.is_empty() {
        tasks.push_str(
            "    respond = Task(\n\
             \x20        description=SYSTEM_PROMPT + \"\\n\\nInput: {input}\",\n\
             \x20        expected_output=\"A helpful response.\",\n\
             \x20        agent=agent,\n\
             \x20    )\n",
        );
        task_names.push("respond".to_string());
    } else {
        for skill in &genome.skill_prompts {
            let var = py_ident(&skill.name);
            tasks.push_str(&format!(
                "    {var} = Task(\n\
                 \x20        description=_load(\"skills/{file}.md\") + \"\\n\\nInput: {{input}}\",\n\
                 \x20        expected_output=\"Result of the {name} skill.\",\n\
                 \x20        agent=agent,\n\
                 \x20    )\n",
                var = var,
                file = py_ident(&skill.name),
                name = skill.name,
            ));
            task_names.push(var);
        }
    }
    let task_list = task_names.join(", ");

    format!(
        r#"{banner}
import os
from pathlib import Path

from crewai import Agent, Crew, Process, Task

PROMPT_DIR = Path(__file__).parent / "prompts"
MODEL = {model:?}
TEMPERATURE = {temperature}
AGENT_ID = {agent_id:?}


def _load(name: str) -> str:
    path = PROMPT_DIR / name
    return path.read_text(encoding="utf-8") if path.exists() else ""


SYSTEM_PROMPT = _load("system.md")


def build_crew() -> Crew:
    # CrewAI reads provider creds from the environment ({key_env}).
    agent = Agent(
        role={name:?},
        goal=SYSTEM_PROMPT or "Assist the user.",
        backstory={description:?},
        llm=MODEL,
        verbose=False,
    )

{tasks}
    return Crew(
        agents=[agent],
        tasks=[{task_list}],
        process=Process.sequential,
    )


crew = build_crew()


if __name__ == "__main__":
    import sys

    user_input = sys.argv[1] if len(sys.argv) > 1 else ""
    print(crew.kickoff(inputs={{"input": user_input}}))
"#,
        banner = banner(genome, "crewai"),
        model = genome.spec.runtime.model_id,
        temperature = temperature_literal(genome),
        agent_id = genome.spec.agent.id,
        key_env = key_env,
        name = genome.spec.agent.name,
        description = genome
            .spec
            .agent
            .description
            .clone()
            .unwrap_or_else(|| format!("{} agent.", genome.spec.agent.name)),
        tasks = tasks,
        task_list = task_list,
    )
}

fn readme(genome: &Genome, provider_label: &str, key_env: &str) -> String {
    format!(
        "# {name} — CrewAI runtime adapter\n\n\
         Auto-generated by `agenomic compile --target crewai` from `{agent_id}`.\n\n\
         Provider: **{provider_label}**, model `{model}`. One Task per declared skill, run sequentially.\n\n\
         ## Run\n\n\
         ```bash\n\
         pip install -r requirements.txt\n\
         export {key_env}=...\n\
         python crew.py \"your input\"\n\
         ```\n",
        name = genome.spec.agent.name,
        agent_id = genome.spec.agent.id,
        provider_label = provider_label,
        model = genome.spec.runtime.model_id,
        key_env = key_env,
    )
}
