//! `docker` target: the `plain` FastAPI service packaged as an OCI image.
//!
//! This is the literal OCI analogy — a deterministic `Dockerfile` that builds
//! the same FastAPI adapter the `plain` target emits, so the agent runs the
//! same everywhere `docker run` does. The Python app files are reused verbatim
//! from [`super::plain`] to avoid drift between the two targets.

use crate::artifact::CompiledArtifact;
use crate::codegen::common::api_key_env;
use crate::codegen::plain;
use crate::genome::Genome;
use crate::target::CompileTarget;

/// Pinned base image. Kept as a constant so the generated `Dockerfile` is
/// byte-stable across runs (no "latest").
const BASE_IMAGE: &str = "python:3.12-slim";

pub(crate) fn generate(genome: &Genome) -> CompiledArtifact {
    let mut a = CompiledArtifact::new(CompileTarget::Docker);
    let key_env = api_key_env(&genome.spec.runtime.model_provider);

    // Reuse the plain FastAPI service (agent.py + requirements.txt).
    plain::emit_fastapi_app(genome, "docker", &mut a);
    a.insert("Dockerfile", dockerfile(key_env));
    a.insert(".dockerignore", dockerignore());
    a.insert("README.md", readme(genome, key_env));
    a
}

fn dockerfile(key_env: &str) -> String {
    format!(
        r#"# Auto-generated by agenomic-compile (target: docker).
# Builds the `plain` FastAPI adapter into an OCI image.
FROM {base}

WORKDIR /app

# Install dependencies first for layer caching.
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Application + embedded prompts.
COPY agent.py ./
COPY prompts ./prompts

# {key_env} must be provided at runtime: `docker run -e {key_env}=... <image>`.
ENV PORT=8080
EXPOSE 8080

CMD ["sh", "-c", "uvicorn agent:app --host 0.0.0.0 --port ${{PORT}}"]
"#,
        base = BASE_IMAGE,
        key_env = key_env,
    )
}

fn dockerignore() -> String {
    // Keep the build context minimal and deterministic.
    "__pycache__/\n*.pyc\n.env\n*.key\n*.pem\nmanifest.json\nREADME.md\n".to_string()
}

fn readme(genome: &Genome, key_env: &str) -> String {
    format!(
        "# {name} — Docker runtime adapter\n\n\
         Auto-generated by `agenomic compile --target docker` from `{agent_id}`.\n\n\
         Packages the `plain` FastAPI service (model `{model}`) as an OCI image.\n\n\
         ## Build & run\n\n\
         ```bash\n\
         docker build -t {tag} .\n\
         docker run --rm -p 8080:8080 -e {key_env}=... {tag}\n\
         # POST http://localhost:8080/invoke  {{\"input\": \"...\"}}\n\
         ```\n\n\
         The image is reproducible: the base image is pinned and the build\n\
         context excludes credentials and the manifest. `manifest.json` pins the\n\
         BLAKE3 of every generated file and the source genome hash.\n",
        name = genome.spec.agent.name,
        agent_id = genome.spec.agent.id,
        model = genome.spec.runtime.model_id,
        tag = genome.agent_slug(),
        key_env = key_env,
    )
}
