//! `plain` target: a FastAPI service that calls the provider SDK directly.

use crate::artifact::CompiledArtifact;
use crate::codegen::common::{
    api_key_env, banner, provider_for, skills_dict, temperature_literal, tools_list,
};
use crate::genome::Genome;
use crate::target::CompileTarget;

pub(crate) fn generate(genome: &Genome) -> CompiledArtifact {
    let mut a = CompiledArtifact::new(CompileTarget::Plain);
    let provider = provider_for(&genome.spec.runtime.model_provider);
    let key_env = api_key_env(&genome.spec.runtime.model_provider);

    emit_fastapi_app(genome, "plain", &mut a);
    a.insert("README.md", readme(genome, provider.label, key_env));
    a
}

/// Insert the shared FastAPI service files (`agent.py`, `requirements.txt`)
/// into `artifact`. Reused by the `docker` target, which wraps the same service
/// in a container. `target_label` only affects the generated-file banner.
pub(crate) fn emit_fastapi_app(
    genome: &Genome,
    target_label: &str,
    artifact: &mut CompiledArtifact,
) {
    let provider = provider_for(&genome.spec.runtime.model_provider);
    let key_env = api_key_env(&genome.spec.runtime.model_provider);
    artifact.insert("agent.py", agent_py(genome, key_env, target_label));
    artifact.insert(
        "requirements.txt",
        format!(
            "fastapi>=0.110\nuvicorn>=0.29\npydantic>=2.6\n{}\n",
            provider.requirement
        ),
    );
}

fn agent_py(genome: &Genome, key_env: &str, target_label: &str) -> String {
    let provider = genome.spec.runtime.model_provider.to_ascii_lowercase();
    let call = match provider.as_str() {
        "anthropic" => anthropic_call(),
        _ => openai_call(),
    };
    let client_init = match provider.as_str() {
        "anthropic" => "client = anthropic.Anthropic(api_key=os.environ[API_KEY_ENV])",
        _ => "client = openai.OpenAI(api_key=os.environ[API_KEY_ENV])",
    };
    let import = match provider.as_str() {
        "anthropic" => "import anthropic",
        _ => "import openai",
    };

    format!(
        r#"{banner}
import os
from pathlib import Path

{import}
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

PROMPT_DIR = Path(__file__).parent / "prompts"
API_KEY_ENV = {key_env:?}
MODEL = {model:?}
TEMPERATURE = {temperature}
AGENT_ID = {agent_id:?}

# Declared MCP tools (stub bindings — wire to your MCP servers to make live).
TOOLS = {tools}

# skill name -> prompt file
SKILLS = {skills}


def _load(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


SYSTEM_PROMPT = _load(PROMPT_DIR / "system.md")

{client_init}
app = FastAPI(title={name:?})


class Invocation(BaseModel):
    input: str
    skill: str | None = None


def _compose_system(skill: str | None) -> str:
    system = SYSTEM_PROMPT
    if skill is not None:
        if skill not in SKILLS:
            raise HTTPException(status_code=404, detail=f"unknown skill: {{skill}}")
        system = (system + "\n\n" + _load(SKILLS[skill])).strip()
    return system


@app.get("/health")
def health() -> dict:
    return {{"status": "ok", "agent": AGENT_ID, "model": MODEL}}


@app.post("/invoke")
def invoke(req: Invocation) -> dict:
    system = _compose_system(req.skill)
{call}
    return {{"output": output, "model": MODEL}}
"#,
        banner = banner(genome, target_label),
        import = import,
        key_env = key_env,
        model = genome.spec.runtime.model_id,
        temperature = temperature_literal(genome),
        agent_id = genome.spec.agent.id,
        tools = tools_list(genome),
        skills = skills_dict(genome),
        client_init = client_init,
        name = genome.spec.agent.name,
        call = call,
    )
}

fn openai_call() -> &'static str {
    r#"    completion = client.chat.completions.create(
        model=MODEL,
        temperature=TEMPERATURE,
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": req.input},
        ],
    )
    output = completion.choices[0].message.content"#
}

fn anthropic_call() -> &'static str {
    r#"    message = client.messages.create(
        model=MODEL,
        temperature=TEMPERATURE,
        max_tokens=1024,
        system=system,
        messages=[{"role": "user", "content": req.input}],
    )
    output = message.content[0].text"#
}

fn readme(genome: &Genome, provider_label: &str, key_env: &str) -> String {
    format!(
        "# {name} — plain runtime adapter\n\n\
         Auto-generated by `agenomic compile --target plain` from `{agent_id}`.\n\n\
         Provider: **{provider_label}**, model `{model}`.\n\n\
         ## Run\n\n\
         ```bash\n\
         pip install -r requirements.txt\n\
         export {key_env}=...\n\
         uvicorn agent:app --reload\n\
         ```\n\n\
         ## Endpoints\n\n\
         - `GET /health`\n\
         - `POST /invoke` — body `{{\"input\": \"...\", \"skill\": \"<optional skill name>\"}}`\n\n\
         `manifest.json` pins the BLAKE3 of every generated file and the source genome hash.\n",
        name = genome.spec.agent.name,
        agent_id = genome.spec.agent.id,
        provider_label = provider_label,
        model = genome.spec.runtime.model_id,
        key_env = key_env,
    )
}
