//! `wasm` target: a `componentize-py` WASM component exporting `invoke.run`.
//!
//! Unlike the server targets, a WASM component has no ambient filesystem, so
//! the system prompt and skill prompts are **inlined** into `app.py` at compile
//! time — the component is fully self-contained and needs no preopened dirs.
//!
//! Outbound model calls require a WASI-HTTP-capable host; the generated `run`
//! attempts the provider SDK call and degrades gracefully when the host does
//! not provide networking (documented in the README and `docs/BACKEND_GAPS.md`).

use crate::artifact::CompiledArtifact;
use crate::codegen::common::{api_key_env, provider_for};
use crate::genome::{py_ident, Genome};
use crate::target::CompileTarget;

pub(crate) fn generate(genome: &Genome) -> CompiledArtifact {
    let mut a = CompiledArtifact::new(CompileTarget::Wasm);
    let provider = provider_for(&genome.spec.runtime.model_provider);
    let key_env = api_key_env(&genome.spec.runtime.model_provider);

    a.insert("wit/agent.wit", wit());
    a.insert("app.py", app_py(genome, key_env));
    a.insert("build.sh", build_sh());
    a.insert(
        "requirements.txt",
        format!("componentize-py>=0.16\n{}\n", provider.requirement),
    );
    a.insert("README.md", readme(genome, provider.label, key_env));
    a
}

fn wit() -> String {
    // A single exported interface keeps the componentize-py binding shape
    // (class-based) predictable.
    r#"package agenomic:agent;

interface invoke {
    /// Run the agent against a single user input and return its output.
    run: func(input: string) -> string;
}

world agent {
    export invoke;
}
"#
    .to_string()
}

fn app_py(genome: &Genome, key_env: &str) -> String {
    let provider = genome.spec.runtime.model_provider.to_ascii_lowercase();

    // Inline the system prompt and every skill prompt as Python literals.
    let system = genome.system_prompt.clone().unwrap_or_default();
    let mut skills = String::from("{\n");
    for skill in &genome.skill_prompts {
        let text = skill.text.clone().unwrap_or_default();
        skills.push_str(&format!("    {:?}: {:?},\n", py_ident(&skill.name), text));
    }
    skills.push('}');

    let call = match provider.as_str() {
        "anthropic" => anthropic_call(),
        _ => openai_call(),
    };

    format!(
        r#"# Auto-generated by agenomic-compile (target: wasm).
# Source agent: {agent_id}
# DO NOT EDIT BY HAND — regenerate with `agenomic compile`.
#
# Implements the `agenomic:agent/invoke` interface for componentize-py.
# Prompts are inlined so the component needs no filesystem access.
import os

import agent  # generated by componentize-py from wit/agent.wit

MODEL = {model:?}
TEMPERATURE = {temperature}
AGENT_ID = {agent_id:?}
API_KEY_ENV = {key_env:?}

SYSTEM_PROMPT = {system:?}
SKILLS = {skills}


def _compose(skill: str) -> str:
    system = SYSTEM_PROMPT
    if skill and skill in SKILLS:
        system = (system + "\n\n" + SKILLS[skill]).strip()
    return system


class Invoke(agent.exports.Invoke):
    def run(self, input: str) -> str:
        # Optional "skill::input" prefix selects a skill.
        skill, _, body = input.partition("::")
        if not body:
            skill, body = "", input
        system = _compose(skill)
        try:
{call}
        except Exception as exc:  # WASI host may lack outbound HTTP
            return f"[agent {{AGENT_ID}}] model call unavailable in this host: {{exc}}"
"#,
        agent_id = genome.spec.agent.id,
        model = genome.spec.runtime.model_id,
        temperature = crate::codegen::common::temperature_literal(genome),
        key_env = key_env,
        system = system,
        skills = skills,
        call = call,
    )
}

fn openai_call() -> &'static str {
    r#"            import openai

            client = openai.OpenAI(api_key=os.environ[API_KEY_ENV])
            completion = client.chat.completions.create(
                model=MODEL,
                temperature=TEMPERATURE,
                messages=[
                    {"role": "system", "content": system},
                    {"role": "user", "content": body},
                ],
            )
            return completion.choices[0].message.content or """#
}

fn anthropic_call() -> &'static str {
    r#"            import anthropic

            client = anthropic.Anthropic(api_key=os.environ[API_KEY_ENV])
            message = client.messages.create(
                model=MODEL,
                temperature=TEMPERATURE,
                max_tokens=1024,
                system=system,
                messages=[{"role": "user", "content": body}],
            )
            return message.content[0].text"#
}

fn build_sh() -> String {
    r#"#!/usr/bin/env bash
# Build the WASM component from app.py against wit/agent.wit.
set -euo pipefail

pip install --no-cache-dir -r requirements.txt
componentize-py --wit-path wit --world agent componentize app -o agent.wasm
echo "wrote agent.wasm"
"#
    .to_string()
}

fn readme(genome: &Genome, provider_label: &str, key_env: &str) -> String {
    format!(
        "# {name} — WASM runtime adapter\n\n\
         Auto-generated by `agenomic compile --target wasm` from `{agent_id}`.\n\n\
         Provider: **{provider_label}**, model `{model}`. Builds a WASI component\n\
         (`componentize-py`) exporting `agenomic:agent/invoke.run`. Prompts are\n\
         inlined into `app.py`, so the component carries no filesystem dependency.\n\n\
         ## Build\n\n\
         ```bash\n\
         ./build.sh        # → agent.wasm\n\
         ```\n\n\
         ## Run\n\n\
         Use any WASI component host (e.g. `wasmtime`, Spin, wasmCloud). Pass\n\
         input as `\"<skill>::<text>\"` to select a skill, or just `\"<text>\"`.\n\n\
         > Note: outbound model calls require a WASI-HTTP-capable host. Without\n\
         > one, `run` returns a diagnostic instead of failing. The credential is\n\
         > read from `{key_env}`.\n",
        name = genome.spec.agent.name,
        agent_id = genome.spec.agent.id,
        provider_label = provider_label,
        model = genome.spec.runtime.model_id,
        key_env = key_env,
    )
}
