import { spawn, type ChildProcess } from 'node:child_process';
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import { createRequire } from 'node:module';
import { paths, type RuntimeConfig } from './config.ts';
import { installCodex } from './hooks-install.ts';
import { isTestCommand, type SessionContext } from './session.ts';
import { errorMessage, executableVersion, log, readExecutableVersion } from './util.ts';
import * as ws from './workspace.ts';

/** Methods this adapter calls. Nothing else of the App Server is reachable from Agenomic. */
const CLIENT_METHODS = new Set(['initialize', 'thread/start', 'thread/resume', 'thread/read', 'turn/start', 'turn/steer', 'turn/interrupt']);

export function codexExecutable(runtime: RuntimeConfig): string {
  if (runtime.executable) return runtime.executable;
  const req = createRequire(import.meta.url);
  const pkg = path.dirname(req.resolve('@openai/codex/package.json'));
  return path.join(pkg, 'bin', 'codex.js');
}

/**
 * Version of the Codex binary a session runs: a configured executable's
 * own (`undefined` until it has answered, see executableVersion), or the
 * pinned package's.
 */
export function codexVersion(runtime: RuntimeConfig): string | null | undefined {
  if (runtime.executable) return executableVersion(runtime.executable);
  return packageVersion();
}

/** codexVersion(), waiting for a configured executable's answer. */
export async function readCodexVersion(runtime: RuntimeConfig): Promise<string | null> {
  if (runtime.executable) return readExecutableVersion(runtime.executable);
  return packageVersion();
}

function packageVersion(): string | null {
  try {
    const req = createRequire(import.meta.url);
    return (req('@openai/codex/package.json') as { version: string }).version;
  } catch {
    return null;
  }
}

interface Pending {
  resolve: (v: any) => void;
  reject: (e: Error) => void;
}

export interface CodexLaunchOptions {
  ctx: SessionContext;
  cwd: string;
  model?: string | null;
  prompt?: string | null;
  resume?: string | null;
  runtime: RuntimeConfig;
  onNativeSession: (nativeId: string) => Promise<void>;
  onStatus: (status: string) => void;
}

/**
 * A Codex session driven through `codex app-server` over stdio. The
 * protocol stays private to this process: the browser and the cloud only
 * see Agenomic commands, never raw App Server methods.
 */
export class CodexSession {
  private child: ChildProcess | undefined;
  private nextId = 1;
  private readonly pending = new Map<number, Pending>();
  private threadId: string | null = null;
  private activeTurn: string | null = null;
  /** Patch content seen on item/started, needed to bind a fileChange approval. */
  private readonly fileChanges = new Map<string, unknown>();
  private readonly itemStart = new Map<string, number>();
  private readonly questions = new Map<string, (answer: string) => void>();
  private ended = false;
  readonly done: Promise<void>;
  private resolveDone!: () => void;

  private readonly o: CodexLaunchOptions;

  constructor(o: CodexLaunchOptions) {
    this.o = o;
    this.done = new Promise((r) => (this.resolveDone = r));
  }

  private codexHome(): string {
    const home = path.join(paths.runtimeHome('codex'), this.o.ctx.id);
    fs.mkdirSync(home, { recursive: true, mode: 0o700 });
    const cfg = [
      '# Generated by agenomic-connector for one coding session. Do not edit.',
      this.o.runtime.extra_config_toml ?? '',
      '',
      // workspace-write also allows /tmp and $TMPDIR by default; a session
      // writes only to its worktree, and has no network.
      '[sandbox_workspace_write]',
      'exclude_slash_tmp = true',
      'exclude_tmpdir_env_var = true',
      'network_access = false',
      '',
    ].join('\n');
    fs.writeFileSync(path.join(home, 'config.toml'), cfg, { mode: 0o600 });
    return home;
  }

  private home = '';

  private env(): Record<string, string> {
    const env: Record<string, string> = {
      PATH: process.env.PATH ?? '/usr/bin:/bin',
      HOME: paths.runtimeHome('codex'),
      CODEX_HOME: this.home,
    };
    for (const k of this.o.runtime.env_passthrough) if (process.env[k]) env[k] = process.env[k]!;
    Object.assign(env, this.o.runtime.extra_env);
    return env;
  }

  private call(method: string, params: unknown, timeoutMs = 60000): Promise<any> {
    if (!CLIENT_METHODS.has(method)) return Promise.reject(new Error(`method ${method} is not exposed`));
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      const t = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`${method} timed out`));
      }, timeoutMs);
      this.pending.set(id, {
        resolve: (v) => {
          clearTimeout(t);
          resolve(v);
        },
        reject: (e) => {
          clearTimeout(t);
          reject(e);
        },
      });
      this.write({ id, method, params });
    });
  }

  private write(msg: unknown): void {
    this.child?.stdin?.write(JSON.stringify(msg) + '\n');
  }

  async start(): Promise<void> {
    const exe = codexExecutable(this.o.runtime);
    this.home = this.codexHome();
    if (this.o.ctx.mode !== 'observe') {
      // The session's own CODEX_HOME carries the trusted PreToolUse hook
      // that routes every shell call to this daemon: fail closed in
      // enforce, open in shadow. The agent cannot write this directory
      // (outside the worktree, workspace-write sandbox).
      const r = await installCodex(path.join(this.home, 'config.toml'), this.o.ctx.mode === 'enforce' ? 'closed' : 'open', exe, this.o.cwd, false, 900, paths.socket());
      if (r.trusted === 0) throw new Error('codex did not report the Agenomic hooks; refusing to start without pre-tool control');
    }
    const args = ['app-server', '--listen', 'stdio://'];
    const command = exe.endsWith('.js') ? process.execPath : exe;
    const argv = exe.endsWith('.js') ? [exe, ...args] : args;
    const child = spawn(command, argv, { cwd: this.o.cwd, env: this.env(), stdio: ['pipe', 'pipe', 'pipe'] });
    this.child = child;
    // A missing or non-executable binary emits 'error' (never 'exit'),
    // which would crash the daemon without a listener: the start is
    // refused instead.
    child.on('error', (e) => log('warn', 'codex process error', { session: this.o.ctx.id, error: e.message }));
    try {
      await new Promise<void>((resolve, reject) => {
        child.once('spawn', resolve);
        child.once('error', reject);
      });
    } catch (error) {
      this.child = undefined;
      this.ended = true;
      this.resolveDone();
      throw new Error(`codex could not be started: ${errorMessage(error)}`);
    }
    child.stderr?.on('data', (d) => log('debug', 'codex stderr', { line: this.o.ctx.cleanText(String(d), 500) }));
    child.on('exit', (code, signal) => {
      this.ended = true;
      for (const p of this.pending.values()) p.reject(new Error('app-server exited'));
      this.pending.clear();
      this.o.ctx.sink.emit('session.ended', 'supervisor', 'native', { exit_code: code, signal });
      this.resolveDone();
    });
    const rl = readline.createInterface({ input: child.stdout! });
    rl.on('line', (line) => void this.onLine(line));

    const init = await this.call('initialize', { clientInfo: { name: 'agenomic-connector', title: 'Agenomic', version: '0.1.0' } });
    log('debug', 'codex initialized', { user_agent: init?.userAgent });
    this.write({ method: 'initialized' });

    const enforce = this.o.ctx.mode === 'enforce';
    const common = {
      cwd: this.o.cwd,
      model: this.o.model ?? undefined,
      // Enforce: every command and patch outside the trusted set asks, and
      // the request is answered by Agenomic. Observe and shadow: Codex
      // never asks (no approver); its sandbox stays the native boundary.
      approvalPolicy: enforce ? 'untrusted' : 'never',
      sandbox: 'workspace-write',
    };
    const res = this.o.resume
      ? await this.call('thread/resume', { threadId: this.o.resume, ...common })
      : await this.call('thread/start', { ...common, ephemeral: false });
    this.threadId = res?.thread?.id ?? null;
    if (!this.threadId) throw new Error('codex did not return a thread id');
    await this.o.onNativeSession(this.threadId);
    this.o.ctx.sink.emit('session.started', 'runtime', 'native', { thread_id: this.threadId, approval_policy: common.approvalPolicy, sandbox: common.sandbox });
    this.o.onStatus('running');
    if (this.o.prompt) await this.send(this.o.prompt);
  }

  private async onLine(line: string): Promise<void> {
    let msg: any;
    try {
      msg = JSON.parse(line);
    } catch {
      return;
    }
    if (msg.id !== undefined && msg.method === undefined) {
      const p = this.pending.get(msg.id);
      this.pending.delete(msg.id);
      if (msg.error) p?.reject(new Error(msg.error.message ?? 'app-server error'));
      else p?.resolve(msg.result);
      return;
    }
    if (msg.id !== undefined && msg.method) {
      await this.onServerRequest(msg.id, msg.method, msg.params ?? {});
      return;
    }
    if (msg.method) this.onNotification(msg.method, msg.params ?? {});
  }

  private respond(id: unknown, result: unknown): void {
    this.write({ id, result });
  }

  private async onServerRequest(id: unknown, method: string, p: any): Promise<void> {
    const ctx = this.o.ctx;
    try {
      if (method === 'item/commandExecution/requestApproval') {
        const isStdin = p.kind === 'stdin';
        const prior = !isStdin && !p.approvalId ? ctx.known(p.itemId) : undefined;
        if (prior) {
          // The PreToolUse hook already decided this exact call.
          this.respond(id, { decision: prior.decision === 'allow' ? 'accept' : 'decline' });
          return;
        }
        const nativeId = p.approvalId ? `${p.itemId}:${p.approvalId}` : `${p.itemId}#approval`;
        const v = await ctx.authorize({
          nativeId,
          tool: isStdin ? 'write_stdin' : 'exec_command',
          input: isStdin ? { session_id: p.itemId, chars: p.command ?? '' } : { cmd: p.command ?? '' },
          context: {
            cwd: p.cwd ?? this.o.cwd,
            workspace_root: this.o.cwd,
            base_revision: ctx.baseRevision,
            sandbox: 'workspace-write',
            permission_mode: 'untrusted',
            network_scope: p.networkApprovalContext ?? null,
          },
          phase: 'native_approval',
          turnId: p.turnId,
          waitForApproval: true,
        });
        // The command item runs under this decision: its tool events and
        // outcome are reported against this action. A stdin write is not
        // the execution of the command item.
        if (!isStdin) ctx.alias(p.itemId, nativeId);
        // One request, one decision: never acceptForSession, never an
        // execpolicy or network amendment the user did not see.
        this.respond(id, { decision: v.decision === 'allow' ? 'accept' : 'decline' });
        return;
      }
      if (method === 'item/fileChange/requestApproval') {
        const changes = this.fileChanges.get(p.itemId) ?? null;
        const patchText = JSON.stringify(changes ?? []);
        const digest = 'sha256:' + createHash('sha256').update(patchText).digest('hex');
        const targets = Array.isArray(changes) ? (changes as any[]).map((c) => c.path).filter(Boolean) : [];
        const v = await ctx.authorize({
          nativeId: p.itemId,
          tool: 'apply_patch',
          input: { changes: changes ?? [], grant_root: p.grantRoot ?? null },
          context: {
            cwd: this.o.cwd,
            workspace_root: this.o.cwd,
            base_revision: ws.headRevision(this.o.cwd) ?? ctx.baseRevision,
            sandbox: 'workspace-write',
            permission_mode: 'untrusted',
            patch_digest: digest,
            paths: targets.map((t: string) => (path.isAbsolute(t) ? t : path.join(this.o.cwd, t))),
          },
          phase: 'native_approval',
          turnId: p.turnId,
          waitForApproval: true,
        });
        // A grantRoot asks for session-wide write access: never granted here.
        this.respond(id, { decision: v.decision === 'allow' && !p.grantRoot ? 'accept' : 'decline' });
        return;
      }
      if (method === 'item/tool/requestUserInput') {
        const qid = String(p.itemId ?? id);
        ctx.sink.emit('question.asked', 'runtime', 'native', { question_id: qid, ...(ctx.capture.conversation ? { questions: p.questions ?? p } : {}) });
        this.o.onStatus('waiting_input');
        const answer = await new Promise<string>((resolve) => this.questions.set(qid, resolve));
        this.questions.delete(qid);
        this.o.onStatus('running');
        ctx.sink.emit('question.answered', 'adapter', 'native', { question_id: qid });
        const answers: Record<string, unknown> = {};
        for (const q of (p.questions ?? []) as any[]) answers[q.id] = { answers: [answer] };
        this.respond(id, { answers });
        return;
      }
      // Anything else (permissions escalation, MCP elicitation, dynamic
      // tools, legacy approvals) is not supported by this adapter: refuse.
      this.write({ id, error: { code: -32601, message: `agenomic-connector does not handle ${method}` } });
      ctx.sink.emit('error', 'adapter', 'native', { code: 'unsupported_server_request', method });
    } catch (error) {
      log('warn', 'codex server request failed', { method, error: errorMessage(error) });
      this.respond(id, { decision: 'decline' });
    }
  }

  private onNotification(method: string, p: any): void {
    const ctx = this.o.ctx;
    const item = p.item ?? {};
    const turn = p.turnId ?? p.turn?.id;
    switch (method) {
      case 'turn/started':
        this.activeTurn = p.turn?.id ?? null;
        ctx.sink.emit('turn.started', 'runtime', 'native', {}, { runtime_turn_id: this.activeTurn ?? undefined });
        break;
      case 'turn/completed': {
        const status = p.turn?.status;
        ctx.sink.emit(status === 'interrupted' ? 'turn.interrupted' : 'turn.completed', 'runtime', 'native', { status }, { runtime_turn_id: p.turn?.id });
        void ctx.settleOpen(`turn ${status ?? 'ended'} before the tool reported`);
        this.activeTurn = null;
        this.snapshotDiff(p.turn?.id);
        this.o.onStatus('idle');
        break;
      }
      case 'thread/tokenUsage/updated': {
        const u = p.tokenUsage?.last ?? p.tokenUsage?.total ?? p.tokenUsage;
        ctx.sink.emit('usage', 'runtime', 'native', {
          input_tokens: u?.inputTokens ?? null,
          output_tokens: u?.outputTokens ?? null,
          basis: u ? 'measured' : 'unavailable',
          cost_usd: null,
          cost_basis: 'unavailable',
        }, { runtime_turn_id: turn });
        break;
      }
      case 'item/started':
        this.itemStart.set(item.id, Date.now());
        if (item.type === 'fileChange') this.fileChanges.set(item.id, item.changes ?? []);
        if (item.type === 'commandExecution') {
          ctx.toolEvent('tool.started', item.id, { native_tool: 'exec_command', ...(ctx.capture.commands ? { command: ctx.cleanText(String(item.command ?? ''), 2000) } : {}) }, { runtime_turn_id: turn });
        }
        if (item.type === 'collabAgentToolCall' || item.type === 'subAgent') ctx.sink.emit('subagent.started', 'runtime', 'native', { item_id: item.id });
        break;
      case 'item/completed': {
        const started = this.itemStart.get(item.id);
        const duration = started ? Date.now() - started : undefined;
        const verdict = ctx.lookup(item.id);
        if (item.type === 'agentMessage') {
          ctx.sink.emit('message.assistant', 'runtime', 'native', ctx.capture.conversation ? { text: ctx.cleanText(String(item.text ?? ''), 16000) } : { length: String(item.text ?? '').length }, { runtime_turn_id: turn });
        } else if (item.type === 'commandExecution') {
          const failed = item.status !== 'completed' || (typeof item.exitCode === 'number' && item.exitCode !== 0);
          ctx.toolEvent(failed ? 'tool.failed' : 'tool.completed', item.id, {
            native_tool: 'exec_command', status: item.status, exit_code: item.exitCode ?? null, duration_ms: duration,
            ...(ctx.capture.commands ? { command: ctx.cleanText(String(item.command ?? ''), 2000) } : {}),
            ...(ctx.capture.outputs ? { output: ctx.cleanText(String(item.aggregatedOutput ?? ''), 4000) } : {}),
          }, { runtime_turn_id: turn });
          if (isTestCommand(item.command)) ctx.sink.emit('test.result', 'adapter', 'derived', { passed: item.exitCode === 0, exit_code: item.exitCode ?? null, basis: 'exit_code' });
          if (item.status === 'declined') void ctx.report(verdict?.actionId, 'unknown', { summary: 'declined, not executed' });
          else void ctx.report(verdict?.actionId, failed ? 'failed' : 'completed', { exit_code: item.exitCode ?? null, duration_ms: duration });
        } else if (item.type === 'fileChange') {
          for (const c of (item.changes ?? []) as any[]) ctx.sink.emit('file.changed', 'runtime', 'native', { path: c.path, kind: c.kind?.type ?? c.kind, status: item.status });
          void ctx.report(verdict?.actionId, item.status === 'completed' ? 'completed' : item.status === 'declined' ? 'unknown' : 'failed', { duration_ms: duration });
          this.fileChanges.delete(item.id);
        } else if (item.type === 'collabAgentToolCall' || item.type === 'subAgent') {
          ctx.sink.emit('subagent.stopped', 'runtime', 'native', { item_id: item.id });
        }
        break;
      }
      default:
        break;
    }
  }

  private snapshotDiff(turn?: string): void {
    const ctx = this.o.ctx;
    if (!ctx.baseRevision) return;
    try {
      const payload: Record<string, unknown> = { base_revision: ctx.baseRevision, files: ws.changes(this.o.cwd, ctx.baseRevision) };
      if (ctx.capture.diffs) {
        const d = ws.diff(this.o.cwd, ctx.baseRevision);
        payload.diff = d.text;
        payload.truncated = d.truncated;
      }
      ctx.sink.emit('diff.snapshot', 'filesystem', 'observed', payload, { runtime_turn_id: turn });
    } catch (error) {
      log('warn', 'diff snapshot failed', { error: errorMessage(error) });
    }
  }

  // ── Commands ──────────────────────────────────────────────────────────

  async send(text: string, expectedTurnId?: string): Promise<'applied' | 'refused'> {
    if (this.ended || !this.threadId) return 'refused';
    const ctx = this.o.ctx;
    ctx.sink.emit('message.user', 'adapter', 'native', ctx.capture.conversation ? { text: ctx.cleanText(text, 16000) } : { length: text.length });
    const input = [{ type: 'text', text }];
    if (this.activeTurn) {
      // Steering needs the active turn id: a stale view is refused.
      await this.call('turn/steer', { threadId: this.threadId, input, expectedTurnId: expectedTurnId ?? this.activeTurn });
    } else {
      await this.call('turn/start', { threadId: this.threadId, input });
    }
    return 'applied';
  }

  answer(questionId: string, text: string): 'applied' | 'refused' {
    const r = this.questions.get(questionId);
    if (!r) return 'refused';
    r(text);
    return 'applied';
  }

  async interrupt(): Promise<'applied' | 'refused' | 'unknown'> {
    if (!this.threadId || !this.activeTurn) return 'refused';
    try {
      await this.call('turn/interrupt', { threadId: this.threadId, turnId: this.activeTurn }, 15000);
      return 'applied';
    } catch (error) {
      log('warn', 'codex interrupt failed', { error: errorMessage(error) });
      return 'unknown';
    }
  }

  async stop(): Promise<'applied' | 'unknown'> {
    void this.o.ctx.settleOpen('session stopped before the tool reported');
    const child = this.child;
    if (!child || child.exitCode !== null || child.signalCode !== null) return 'applied';
    child.stdin?.end();
    const exited = await new Promise<boolean>((resolve) => {
      const t = setTimeout(() => {
        child.kill('SIGTERM');
        setTimeout(() => {
          if (child.exitCode === null && child.signalCode === null) child.kill('SIGKILL');
          setTimeout(() => resolve(child.exitCode !== null || child.signalCode !== null), 1000);
        }, 3000);
      }, 2000);
      child.once('exit', () => {
        clearTimeout(t);
        resolve(true);
      });
    });
    return exited ? 'applied' : 'unknown';
  }

  alive(): boolean {
    return !this.ended && !!this.child && this.child.exitCode === null && this.child.signalCode === null;
  }

  native(): string | null {
    return this.threadId;
  }
}
